---
# serverless.yml

service: my-serverless-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: $(opt:stage, 'dev')
  region: ap-southeast-2
  environment:
    stage: ${opt:stage, 'dev'}
    

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
...
